# Generated by Django 3.1.7 on 2021-03-31 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210329_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('price', models.IntegerField(default='')),
                ('phone', models.CharField(max_length=13)),
                ('message', models.CharField(max_length=300)),
            ],
        ),
    ]
